version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      # These variables will be used locally; in production, set them via Heroku config vars.
      - DATABASE_URL=postgres://postgres:password@db:5432/node
      - ALCHEMY_API_KEY=your_alchemy_api_key
      - BUNDLE_TRACKER_ADDRESS=your_bundle_tracker_contract_address
      - PROPOSER_KEY=your_private_key
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: node
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
